name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Push to Hugging Face Spaces
        env:
          HF_TOKEN: ${{ secrets.HG}}
        run: |
          git clone https://$HG@huggingface.co/spaces/trung06042002/demo hf-space
          rsync -av --exclude='.git' --exclude='hf-space' ./ hf-space/
          cd hf-space
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "auto deploy from GitHub" || echo "No changes to commit"
          git push https://$HG@huggingface.co/spaces/trung06042002/demo
