name: Sync to Hugging Face hub

on:
  push:
    branches: [main]

  # Cho phép chạy workflow này thủ công từ tab Actions
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Checkout source code từ GitHub repo
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Bước 2: Thêm remote Hugging Face Space
      - name: Add remote
        env:
          HF: ${{ secrets.HG }}
        run: |
          git remote add space https://trung06042002:$HG@huggingface.co/spaces/trung06042002/demo

      # Bước 3: Push code lên Hugging Face Space
      - name: Push to hub
        env:
          HF: ${{ secrets.HG }}
        run: |
          git push --force https://trung06042002:$HG@huggingface.co/spaces/trung06042002/demo main
