name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git config
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "Your Name"

      - name: Push to Hugging Face Spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git clone https://huggingface.co/spaces/trung06042002/demo hf-space
          cp -r * hf-space/
          cd hf-space
          git add .
          git commit -m "auto deploy from GitHub"
          git push
